name: hyper_effects
description: Create beautiful effects and animations with just a few lines of code.

version: 0.2.3

homepage: https://hyperdesigned.dev/
repository: https://github.com/hyper-designed/hyper_effects
issue_tracker: https://github.com/hyper-designed/hyper_effects/issues

screenshots:
  - description: Hyper Effects by hyperdesigned.dev
    path: screenshots/logo.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  unicode_emojis: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

topics:
  - animation
  - effects
  - transitions
  - scroll-effects
